[google_auth]
client_id = "your-client-id.apps.googleusercontent.com"
client_secret = "your-client-secret"
redirect_uri = "https://your-app-name.streamlit.app"  # For production
# redirect_uri = "http://localhost:8501"  # For local development
